disabled_rules:
  - type_body_length
  - trailing_whitespace
  - file_length
  - variable_name
  - valid_docs
  - vertical_whitespace
  - redundant_discardable_let
  - unused_optional_binding

# review with team
colon:
    flexible_right_spacing: true

excluded:
  - Pods
  - AxxessCARETests
  - DuctTapeUITests

line_length:
  - 150 # Warning

function_body_length:
  - 150 # Warning
  - 250 # Error

cyclomatic_complexity:
  - 15 # Warning

reporter: "xcode"

# opt_in_rules: # some rules are only opt-in
#   - empty_count
#   # Find all the available rules by running:
#   # swiftlint rules
# included: # paths to include during linting. `--path` is ignored if present.
#   - Source
# excluded: # paths to ignore during linting. Takes precedence over `included`.
#   - Pods
#   - WWCodeDFWTests
#   - WWCodeDFWUITests

# # configurable rules can be customized from this configuration file
# # binary rules can set their severity level
# force_cast: warning # implicitly
# force_try:
#   severity: warning # explicitly
# # rules that have both warning and error levels, can set just the warning level
# # implicitly
# line_length: 110
# # they can set both implicitly with an array
# type_body_length:
#   - 300 # warning
#   - 400 # error
# # or they can set both explicitly
# file_length:
#   warning: 500
#   error: 1200
# # naming rules can set warnings/errors for min_length and max_length
# # additionally they can set excluded names
# type_name:
#   min_length: 4 # only warning
#   max_length: # warning and error
#     warning: 40
#     error: 50
#   excluded: iPhone # excluded via string
# identifier_name:
#   min_length: # only min_length
#     error: 4 # only error
#   excluded: # excluded via string array
#     - id
#     - URL
#     - GlobalAPIKey
# reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)